"""add system role

Revision ID: b9fc65d514ec
Revises: 8c080da941a4
Create Date: 2026-07-03 21:40:49.738488

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9fc65d514ec"
down_revision: Union[str, Sequence[str], None] = "8c080da941a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE messagerole " "ADD VALUE IF NOT EXISTS 'system';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    raise NotImplementedError("Downgrading enum changes is not supported.")
    # ### end Alembic commands ###
