"""Domain models and contracts."""

from chat_buddy.characters.domain.continuity import (
    Continuity,
    ContinuityGroup,
    ContinuityLifecycle,
    ContinuityMode,
    RelationshipIntent,
    RelationshipSelection,
    StartContinuity,
    StartingOrigins,
    StartingRelationship,
)
from chat_buddy.characters.domain.errors import (
    ActiveContinuityError,
    ArchivedContinuityError,
    ConfirmationConflictError,
    ContinuityNotFoundError,
    FrozenIdentityError,
    FrozenPersonaError,
    IdentityNotFoundError,
    InvalidProviderResponseError,
    ModelResolutionError,
    PersonaNotFoundError,
    ProviderInvocationError,
    StaleIdentityError,
    StalePersonaError,
    UnsupportedContinuityModeError,
    UnsupportedGenerationError,
)
from chat_buddy.characters.domain.identity import Identity, IdentityDetails
from chat_buddy.characters.domain.llm import (
    EffectiveGeneration,
    GenerationConfiguration,
    ModelDescriptor,
    ModelRegistry,
    PromptMessage,
    ResponseGateway,
    SummaryGateway,
    TokenCounter,
)
from chat_buddy.characters.domain.persona import Persona, PersonaCore

__all__ = [
    "ActiveContinuityError",
    "ArchivedContinuityError",
    "ConfirmationConflictError",
    "Continuity",
    "ContinuityGroup",
    "ContinuityLifecycle",
    "ContinuityMode",
    "ContinuityNotFoundError",
    "EffectiveGeneration",
    "FrozenIdentityError",
    "FrozenPersonaError",
    "GenerationConfiguration",
    "Identity",
    "IdentityDetails",
    "IdentityNotFoundError",
    "InvalidProviderResponseError",
    "ModelDescriptor",
    "ModelRegistry",
    "ModelResolutionError",
    "Persona",
    "PersonaCore",
    "PersonaNotFoundError",
    "PromptMessage",
    "ProviderInvocationError",
    "RelationshipIntent",
    "RelationshipSelection",
    "ResponseGateway",
    "StaleIdentityError",
    "StalePersonaError",
    "StartContinuity",
    "StartingOrigins",
    "StartingRelationship",
    "SummaryGateway",
    "TokenCounter",
    "UnsupportedContinuityModeError",
    "UnsupportedGenerationError",
]
